### ISSUE TITLE
Deprecated selectors

### ISSUE THREAD

**Issue by fiws** [mthadley/outlander-ui#2]
in  index.less
* Use the `atom-workspace` tag instead of the `workspace` class.
* Use the `atom-text-editor` tag instead of the `editor` class.
* Use the selector `atom-text-editor[mini]` to select mini-editors.
* Use the `atom-pane` tag instead of the `pane` class.

Can you fix my favourite theme? :)

**Comment by mthadley** [comment]
Will do. Some of those class selectors were left in alongside their tag selector equivalents because it was possible for the user to not have the Shadow DOM option enabled. Since that option is now at least disabled by default, I think I should be able to remove all of these deprecated selectors.

Should be fixed soon! Thanks!
